[package]
name = "jp-prefecture"
version = "0.1.0"
authors = ["Ittoh Kimura <kimura.itto.kd3@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.10.0"
thiserror = "1.0.30"

[dev-dependencies]
test-case = "2.0.2"