name: Test

on:
  push:
    branches: ["**"]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUSTC_FORCE_INCREMENTAL: 1

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        name: Install stable
        with:
          toolchain: stable-x86_64-unknown-linux-gnu
          profile: minimal
          override: true
          components: rustfmt, clippy

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: check
        run: |
          cargo check --all --verbose

      - name: Run format
        run: |
          cargo fmt --check --all --verbose

      - name: Run lint
        run: |
          cargo clippy

      - name: Run test
        run: |
          cargo test --verbose